clean_teams_pff_to_cfbd <- function(x){x <- case_match(x,
                                                       'ABILENE CH' ~ 'Abilene Christian',
                                                       'ALAB A&M'   ~ 'Alabama A&M',
                                                       'ALABAMA ST' ~ 'Alabama State',
                                                       'ALBANY ST'  ~ 'Albany State',
                                                       'ALCORN ST'  ~ 'Alcorn State',
                                                       'AMRINT'     ~ 'American International',
                                                       'ANG ST'     ~ 'Angelo State',
                                                       "APP STATE"  ~ "Appalachian State",
                                                       "ARIZONA ST" ~ "Arizona State",
                                                       'ARKAPB'     ~ 'Arkansas-Pine Bluff',
                                                       "ARK STATE"  ~ "Arkansas State",
                                                       'ASSMPT'     ~ 'Assumption',
                                                       'AUSTINPEAY' ~ 'Austin Peay',
                                                       'AVEMAR'     ~ 'Ave Maria',
                                                       "BALL ST"    ~ "Ball State",
                                                       'BARCOL'     ~ 'Barton College',
                                                       'BETH COOK'  ~ 'Bethune-Cookman',
                                                       'BLMSBG'     ~ 'Bloomsburg',
                                                       "BOISE ST"   ~ "Boise State",
                                                       "BOSTON COL" ~ "Boston College",
                                                       "BOWL GREEN" ~ "Bowling Green",
                                                       "BYU"        ~ "BYU",
                                                       "CAL"        ~ "California",
                                                       'CATAWB'     ~ 'Catawba',
                                                       'CENT ARK'   ~ 'Central Arkansas',
                                                       "C MICHIGAN" ~ "Central Michigan",
                                                       'CENT WASH'  ~ 'Central Washington',
                                                       'CHADST'     ~ 'Chadron State',
                                                       'CHAPMA'     ~ 'Chapman',
                                                       'CHARLES SO' ~ 'Charleston Southern',
                                                       'CHATTNOOGA' ~ 'Chattanooga',
                                                       "COAST CAR"  ~ "Coastal Carolina",
                                                       "COLO STATE" ~ "Colorado State",
                                                       'CONCMI'     ~ 'Concordia College (MI)',
                                                       "UCONN"      ~ "Connecticut",
                                                       'DELWARE ST' ~ 'Delaware State',
                                                       'DELTAST'    ~ 'Delta State',
                                                       'DEPAUW'     ~ 'DePauw',
                                                       "E CAROLINA" ~ "East Carolina",
                                                       'EAST CENT'  ~ 'East Central',
                                                       'E ILLINOIS' ~ 'Eastern Illinois',
                                                       'E KENTUCKY' ~ 'Eastern Kentucky',
                                                       "E MICHIGAN" ~ "Eastern Michigan",
                                                       'E TENN ST'  ~ 'Eastern Tennessee State',
                                                       "E WASHGTON" ~ "Eastern Washington",
                                                       'ED WATERS'  ~ 'Edward Waters',
                                                       'ELIZBTH ST' ~ 'Elizabeth City State',
                                                       'FLKNR'      ~ 'Faulkner',
                                                       'FERRIS'     ~ 'Ferris State',
                                                       "FL A&M"     ~ "Florida A&M",
                                                       "FAU"        ~ "Florida Atlantic",
                                                       "FIU"        ~ "Florida International",
                                                       'FLMMRL'     ~ 'Florida Memorial University',
                                                       "FLORIDA ST" ~ "Florida State",
                                                       'FORT LEW'   ~ 'Fort Lewis',
                                                       'FRTVLY'     ~ 'Fort Valley State',
                                                       "FRESNO ST"  ~ "Fresno State",
                                                       'GARD-WEBB'  ~ 'Gardner-Webb',
                                                       "GA SOUTHRN" ~ "Georgia Southern",
                                                       "GA STATE"   ~ "Georgia State",
                                                       "GA TECH"    ~ "Georgia Tech",
                                                       'GUSTAV'     ~ 'Gustavus Adolphus',
                                                       'HAMLIN'     ~ 'Hamline',
                                                       'HAMPTON'    ~ 'Hampton',
                                                       "HAWAII"     ~ "Hawai'i",
                                                       'HOUCHR'     ~ 'Houston Christian',
                                                       'IDAHO ST'   ~ 'Idaho State',
                                                       "ILL STATE"  ~ "Illinois State",
                                                       'INCAR WORD' ~ 'Incarnate Word',
                                                       'INDIANA ST' ~ 'Indiana State',
                                                       'INWSLY'     ~ 'Indiana Wesleyan',
                                                       'JACKSON ST' ~ 'Jackson State',
                                                       'JVILLE'     ~ 'Jacksonville',
                                                       "JVILLE ST"  ~ "Jacksonville State",
                                                       "JAMES MAD"  ~ "James Madison",
                                                       "KANSAS ST"  ~ "Kansas State",
                                                       'KEISER'     ~ 'Keiser University',
                                                       'KENNESAW'   ~ 'Kennesaw State',
                                                       'KY STATE'   ~ 'Kentucky State',
                                                       'LANECOL'    ~ 'Laney College',
                                                       'LENOIR'     ~ 'Lenoir-Rhyne',
                                                       "LA LAFAYET" ~ "Louisiana",
                                                       'LOUCOL'     ~ 'Louisiana College',
                                                       "LA MONROE"  ~ "Louisiana Monroe",
                                                       "LA TECH"    ~ "Louisiana Tech",
                                                       "LSU"        ~ "LSU",
                                                       "MIAMI FL"   ~ "Miami",
                                                       "MIAMI OH"   ~ "Miami (OH)",
                                                       "MICH STATE" ~ "Michigan State",
                                                       "MIDDLE TN"  ~ "Middle Tennessee",
                                                       'MISS COL'   ~ 'Mississippi College',
                                                       "MISS STATE" ~ "Mississippi State",
                                                       'MS VLY ST'  ~ 'Mississippi Valley State',
                                                       'MO STATE'   ~ 'Missouri State',
                                                       'MO WE ST'   ~ 'Missouri Western State',
                                                       'MONTANA ST' ~ 'Montana State',
                                                       'MOREHEAD'   ~ 'Morehead State',
                                                       'MORGAN ST'  ~ 'Morgan State',
                                                       'MURRAY ST'  ~ 'Murray State',
                                                       "NC STATE"   ~ "NC State",
                                                       'NEW HAMP'   ~ 'New Hampshire',
                                                       'N MEX HIGH' ~ 'New Mexico Highland',
                                                       "NEW MEX ST" ~ "New Mexico State",
                                                       'NEWBER'     ~ 'Newberry',
                                                       'NORFOLK'    ~ 'Norfolk State',
                                                       'N ALABAMA'  ~ 'North Alabama',
                                                       "N CAROLINA" ~ "North Carolina",
                                                       "NC A&T"     ~ "North Carolina A&T",
                                                       'NC CENT'    ~ 'North Carolina Central',
                                                       'N DAKOTA'   ~ 'North Dakota',
                                                       "N DAK ST"   ~ "North Dakota State",
                                                       'NORTHEA ST' ~ 'Northeastern State',
                                                       "N TEXAS"    ~ "North Texas",
                                                       "N ARIZONA"  ~ "Northern Arizona",
                                                       "N COLORADO" ~ "Northern Colorado",
                                                       "N ILLINOIS" ~ "Northern Illinois",
                                                       "N IOWA"     ~ "Northern Iowa",
                                                       "NWESTERN"   ~ "Northwestern",
                                                       'NWSTATE'    ~ 'Northwestern State',
                                                       "OKLA STATE" ~ "Oklahoma State",
                                                       "DOMINION"   ~ "Old Dominion",
                                                       "OREGON ST"  ~ "Oregon State",
                                                       'PRVIEW A&M' ~ 'Prairie View',
                                                       'PRESBYTERN' ~ 'Presbyterian College',
                                                       'RHODE ISLD' ~ 'Rhode Island',
                                                       'ROB MORRIS' ~ 'Robert Morris',
                                                       'ROSEHU'     ~ 'Rose-Hulman',
                                                       'SACRAMENTO' ~ 'Sacramento State',
                                                       'SACR HEART' ~ 'Sacred Heart',
                                                       "SM HOUSTON" ~ "Sam Houston State",
                                                       "S DIEGO ST" ~ "San Diego State",
                                                       "S JOSE ST"  ~ "San José State",
                                                       'SVANNAH ST' ~ 'Savannah State',
                                                       'SIMONFRA'   ~ 'Simon Fraser',
                                                       "SMU"        ~ "SMU",
                                                       "S ALABAMA"  ~ "South Alabama",
                                                       "S CAROLINA" ~ "South Carolina",
                                                       'SCAR STATE' ~ 'South Carolina State',
                                                       'S DAKOTA'   ~ 'South Dakota',
                                                       "S DAK ST"   ~ "South Dakota State",
                                                       "USF"        ~ "South Florida",
                                                       'SE MO ST'   ~ 'Southeast Missouri State',
                                                       'SE LA'      ~ 'Southeastern Louisiana',
                                                       'S ILLINOIS' ~ 'Southern Illinois',
                                                       "SO MISS"    ~ "Southern Mississippi",
                                                       'SO UTAH'    ~ 'Southern Utah',
                                                       'SW BAPTIST' ~ 'Southwest Baptist',
                                                       'SWMINN'     ~ 'Southwest Minnesota',
                                                       'ST ANSELM'  ~ 'St. Anselm',
                                                       'ST AUGSTNE' ~ "St. Augustine's",
                                                       'STOLAF'     ~ 'St. Olaf College',
                                                       'STF AUSTIN' ~ 'Stephen F. Austin',
                                                       'STNY BROOK' ~ 'Stony Brook',
                                                       'TARLETON'   ~ 'Tarleton State',
                                                       "TCU"        ~ "TCU",
                                                       "TENN STATE" ~ "Tennessee State",
                                                       'TENN TECH'  ~ 'Tennessee Tech',
                                                       'TXAMCO'     ~ 'Texas A&M-Commerce',
                                                       'TXPERB'     ~ 'Texas-Permian Basin',
                                                       'TEXAS STHN' ~ 'Texas Southern',
                                                       "TEXAS ST"   ~ "Texas State",
                                                       'TXWSLY'     ~ 'Texas Wesleyan',
                                                       'THMORE'     ~ 'Thomas More',
                                                       'TUSCUL'     ~ 'Tusculum',
                                                       "UAB"        ~ "UAB",
                                                       "UCF"        ~ "UCF",
                                                       "UCLA"       ~ "UCLA",
                                                       "UMASS"      ~ "UMass",
                                                       "UNLV"       ~ "UNLV",
                                                       "USC"        ~ "USC",
                                                       'TENN MARTN' ~ 'UT Martin',
                                                       "UTSA"       ~ "UT San Antonio",
                                                       "UTAH ST"    ~ "Utah State",
                                                       'UTAHTC'     ~ 'Utah Tech',
                                                       "UTEP"       ~ "UTEP",
                                                       'UVAWIS'     ~ 'UVA-Wise',
                                                       'VALPO'      ~ 'Valparaiso',
                                                       'VA LYNCHBU' ~ 'Virginia Lynchburg',
                                                       'VIRSTA'     ~ 'Virginia State',
                                                       "VA TECH"    ~ "Virginia Tech",
                                                       'VA MILT IN' ~ 'VMI',
                                                       'WABASH'     ~ 'Wabash College',
                                                       "WAKE"       ~ "Wake Forest",
                                                       "WASH STATE" ~ "Washington State",
                                                       "WEBER ST"   ~ "Weber State",
                                                       'WESTFL'     ~ 'West Florida',
                                                       'WE TEX AM'  ~ 'West Texas A&M',
                                                       "W VIRGINIA" ~ "West Virginia",
                                                       'W CAROLINA' ~ 'Western Carolina',
                                                       'W ILLINOIS' ~ 'Western Illinois',
                                                       "W KENTUCKY" ~ "Western Kentucky",
                                                       "W MICHIGAN" ~ "Western Michigan",
                                                       'W OREGON'   ~ 'Western Oregon',
                                                       'WHEATO'     ~ 'Wheaton College (Ill)',
                                                       'WM & MARY'  ~ 'William & Mary',
                                                       'WJWLL'      ~ 'William Jewell College',
                                                       'WINGAT'     ~ 'Wingate',
                                                       'WISCSP'     ~ 'Wisconsin-Stevens Point',
                                                       'YNGTWON ST' ~ 'Youngstown State',
                                                       TRUE ~ str_to_title(x))}
